apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-quarkus-application
spec:
  params:
    - default: coffee-shop
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: 'false'
      description: Parameter to deploy serverless app
      name: DEPLOY_SERVERLESS
      type: string
    - default: latest
      description: Parameter to the final image
      name: IMAGE
      type: string
    - default: hd5f5-dev-coffeeshop
      description: Namespace where the buildconfig is located
      name: NAMESPACE_DEV
      type: string
  tasks:

  tasks:
    - name: set-kn-in-dev
      params:
        - name: ARGS
          value:
            - service
            - update
            - $(params.APP_NAME)
            - '--image=$(params.IMAGE)'
            - '--namespace=$(params.NAMESPACE_DEV)'
      taskRef:
        kind: ClusterTask
        name: kn
      when:
        - Input: $(params.DEPLOY_SERVERLESS)
          Operator: in
          Values:
            - 'true'
    - name: set-image-in-dev
      params:
        - name: ARGS
          value:
            - set
            - image
            - deployment
            - $(params.APP_NAME)
            - $(params.APP_NAME)=$(params.IMAGE)
            - '-n $(params.NAMESPACE_DEV)'
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - Input: $(params.DEPLOY_SERVERLESS)
          Operator: in
          Values:
            - 'false'
