apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: image-registry.openshift-image-registry.svc:5000/user25-dev-coffeeshop/barista:dev-2022-03-22-17-34-45

