apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: coffee-shop
    app.openshift.io/runtime: quarkus
  name: coffee-shop
spec:
  lookupPolicy:
    local: false
