apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- barista.yaml
- coffee-shop-database.yaml
- coffee-shop.yaml
patches:
- path: syncpolicy-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
