---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: nexus-registry-nexus.apps.cluster-fc9tk.fc9tk.sandbox302.opentlc.com/user25-coffee-shop:prod-2022-03-22-17-06-54
