apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: set-image-
spec:
  taskRef:
    kind: ClusterTask
    name: openshift-client
  params:
  - name: SCRIPT
    value: >-
      oc set image deployment coffee-shop
      coffee-shop=image-registry.openshift-image-registry.svc:5000/user25-dev-coffeeshop/coffee-shop:dev-2022-03-24-23-10-33
      -n user25-dev-coffeeshop
