apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: publish-image-
spec:
  taskRef:
    kind: ClusterTask
    name: skopeo-copy
  params:
  - name: srcImageURL
    value: docker://image-registry.openshift-image-registry.svc:5000/user25-dev-coffeeshop/coffee-shop:prod-2022-03-24-23-10-33
  - name: srcTLSverify
    value: "false"
  - name: destImageURL
    value: docker://nexus-registry.nexus.svc:5000/user25-coffee-shop:prod-2022-03-24-23-10-33
  - name: destTLSverify
    value: "false"
  workspaces:
  - name: images-url
    emptyDir: {}
